### ISSUE TITLE
Output JSON

### ISSUE THREAD

**Issue by GuillaumeDesforges** [tweag/ponyrep#1]
**Is your feature request related to a problem? Please describe.**
I want to pipe the output of this tool to other CLI commands, or perform a complex formatting.

**Describe the solution you'd like**
I'd like a flag `--json` which makes the output display as JSON to sdout.

**Comment by rapenne-s** [comment]
`ponyrep --json tweag/ponyrep` is now a thing

```
[
  {
    "url": "https://api.github.com/repos/tweag/ponyrep/issues/1",
    "when": "2022-11-10 11:44:51 UTC",
    "who": "GuillaumeDesforges",
    "category": "OPEN 1",
    "what": "Output JSON"
  }
]
```

Format will certainly evolve because it's currently simplistic.
